/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RaporteRouteImport } from './routes/raporte'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DosjetRouteImport } from './routes/dosjet'
import { Route as BiznesRouteImport } from './routes/biznes'
import { Route as AplikimRouteImport } from './routes/aplikim'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackCodeRouteImport } from './routes/track.$code'
import { Route as DosjaIdRouteImport } from './routes/dosja.$id'
import { Route as AplikimDokumentacionRouteImport } from './routes/aplikim.dokumentacion'
import { Route as ApiPublicFaqAssistRouteImport } from './routes/api/public/faq-assist'
import { Route as ApiPublicExtractRouteImport } from './routes/api/public/extract'
import { Route as ApiPublicDossiersRouteImport } from './routes/api/public/dossiers'
import { Route as ApiPublicDashboardRouteImport } from './routes/api/public/dashboard'
import { Route as ApiAiSummaryRouteImport } from './routes/api/ai/summary'
import { Route as ApiAiNextStepRouteImport } from './routes/api/ai/next-step'
import { Route as ApiAiAssistRouteImport } from './routes/api/ai/assist'
import { Route as ApiPublicTrackCodeRouteImport } from './routes/api/public/track.$code'
import { Route as ApiPublicDossiersIdRouteImport } from './routes/api/public/dossiers.$id'

const RaporteRoute = RaporteRouteImport.update({
  id: '/raporte',
  path: '/raporte',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DosjetRoute = DosjetRouteImport.update({
  id: '/dosjet',
  path: '/dosjet',
  getParentRoute: () => rootRouteImport,
} as any)
const BiznesRoute = BiznesRouteImport.update({
  id: '/biznes',
  path: '/biznes',
  getParentRoute: () => rootRouteImport,
} as any)
const AplikimRoute = AplikimRouteImport.update({
  id: '/aplikim',
  path: '/aplikim',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackCodeRoute = TrackCodeRouteImport.update({
  id: '/track/$code',
  path: '/track/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const DosjaIdRoute = DosjaIdRouteImport.update({
  id: '/dosja/$id',
  path: '/dosja/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AplikimDokumentacionRoute = AplikimDokumentacionRouteImport.update({
  id: '/dokumentacion',
  path: '/dokumentacion',
  getParentRoute: () => AplikimRoute,
} as any)
const ApiPublicFaqAssistRoute = ApiPublicFaqAssistRouteImport.update({
  id: '/api/public/faq-assist',
  path: '/api/public/faq-assist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicExtractRoute = ApiPublicExtractRouteImport.update({
  id: '/api/public/extract',
  path: '/api/public/extract',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDossiersRoute = ApiPublicDossiersRouteImport.update({
  id: '/api/public/dossiers',
  path: '/api/public/dossiers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDashboardRoute = ApiPublicDashboardRouteImport.update({
  id: '/api/public/dashboard',
  path: '/api/public/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiSummaryRoute = ApiAiSummaryRouteImport.update({
  id: '/api/ai/summary',
  path: '/api/ai/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiNextStepRoute = ApiAiNextStepRouteImport.update({
  id: '/api/ai/next-step',
  path: '/api/ai/next-step',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiAssistRoute = ApiAiAssistRouteImport.update({
  id: '/api/ai/assist',
  path: '/api/ai/assist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTrackCodeRoute = ApiPublicTrackCodeRouteImport.update({
  id: '/api/public/track/$code',
  path: '/api/public/track/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDossiersIdRoute = ApiPublicDossiersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPublicDossiersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/aplikim': typeof AplikimRouteWithChildren
  '/biznes': typeof BiznesRoute
  '/dosjet': typeof DosjetRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/raporte': typeof RaporteRoute
  '/aplikim/dokumentacion': typeof AplikimDokumentacionRoute
  '/dosja/$id': typeof DosjaIdRoute
  '/track/$code': typeof TrackCodeRoute
  '/api/ai/assist': typeof ApiAiAssistRoute
  '/api/ai/next-step': typeof ApiAiNextStepRoute
  '/api/ai/summary': typeof ApiAiSummaryRoute
  '/api/public/dashboard': typeof ApiPublicDashboardRoute
  '/api/public/dossiers': typeof ApiPublicDossiersRouteWithChildren
  '/api/public/extract': typeof ApiPublicExtractRoute
  '/api/public/faq-assist': typeof ApiPublicFaqAssistRoute
  '/api/public/dossiers/$id': typeof ApiPublicDossiersIdRoute
  '/api/public/track/$code': typeof ApiPublicTrackCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/aplikim': typeof AplikimRouteWithChildren
  '/biznes': typeof BiznesRoute
  '/dosjet': typeof DosjetRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/raporte': typeof RaporteRoute
  '/aplikim/dokumentacion': typeof AplikimDokumentacionRoute
  '/dosja/$id': typeof DosjaIdRoute
  '/track/$code': typeof TrackCodeRoute
  '/api/ai/assist': typeof ApiAiAssistRoute
  '/api/ai/next-step': typeof ApiAiNextStepRoute
  '/api/ai/summary': typeof ApiAiSummaryRoute
  '/api/public/dashboard': typeof ApiPublicDashboardRoute
  '/api/public/dossiers': typeof ApiPublicDossiersRouteWithChildren
  '/api/public/extract': typeof ApiPublicExtractRoute
  '/api/public/faq-assist': typeof ApiPublicFaqAssistRoute
  '/api/public/dossiers/$id': typeof ApiPublicDossiersIdRoute
  '/api/public/track/$code': typeof ApiPublicTrackCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/aplikim': typeof AplikimRouteWithChildren
  '/biznes': typeof BiznesRoute
  '/dosjet': typeof DosjetRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/raporte': typeof RaporteRoute
  '/aplikim/dokumentacion': typeof AplikimDokumentacionRoute
  '/dosja/$id': typeof DosjaIdRoute
  '/track/$code': typeof TrackCodeRoute
  '/api/ai/assist': typeof ApiAiAssistRoute
  '/api/ai/next-step': typeof ApiAiNextStepRoute
  '/api/ai/summary': typeof ApiAiSummaryRoute
  '/api/public/dashboard': typeof ApiPublicDashboardRoute
  '/api/public/dossiers': typeof ApiPublicDossiersRouteWithChildren
  '/api/public/extract': typeof ApiPublicExtractRoute
  '/api/public/faq-assist': typeof ApiPublicFaqAssistRoute
  '/api/public/dossiers/$id': typeof ApiPublicDossiersIdRoute
  '/api/public/track/$code': typeof ApiPublicTrackCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-login'
    | '/aplikim'
    | '/biznes'
    | '/dosjet'
    | '/faq'
    | '/login'
    | '/raporte'
    | '/aplikim/dokumentacion'
    | '/dosja/$id'
    | '/track/$code'
    | '/api/ai/assist'
    | '/api/ai/next-step'
    | '/api/ai/summary'
    | '/api/public/dashboard'
    | '/api/public/dossiers'
    | '/api/public/extract'
    | '/api/public/faq-assist'
    | '/api/public/dossiers/$id'
    | '/api/public/track/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login'
    | '/aplikim'
    | '/biznes'
    | '/dosjet'
    | '/faq'
    | '/login'
    | '/raporte'
    | '/aplikim/dokumentacion'
    | '/dosja/$id'
    | '/track/$code'
    | '/api/ai/assist'
    | '/api/ai/next-step'
    | '/api/ai/summary'
    | '/api/public/dashboard'
    | '/api/public/dossiers'
    | '/api/public/extract'
    | '/api/public/faq-assist'
    | '/api/public/dossiers/$id'
    | '/api/public/track/$code'
  id:
    | '__root__'
    | '/'
    | '/admin-login'
    | '/aplikim'
    | '/biznes'
    | '/dosjet'
    | '/faq'
    | '/login'
    | '/raporte'
    | '/aplikim/dokumentacion'
    | '/dosja/$id'
    | '/track/$code'
    | '/api/ai/assist'
    | '/api/ai/next-step'
    | '/api/ai/summary'
    | '/api/public/dashboard'
    | '/api/public/dossiers'
    | '/api/public/extract'
    | '/api/public/faq-assist'
    | '/api/public/dossiers/$id'
    | '/api/public/track/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AplikimRoute: typeof AplikimRouteWithChildren
  BiznesRoute: typeof BiznesRoute
  DosjetRoute: typeof DosjetRoute
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  RaporteRoute: typeof RaporteRoute
  DosjaIdRoute: typeof DosjaIdRoute
  TrackCodeRoute: typeof TrackCodeRoute
  ApiAiAssistRoute: typeof ApiAiAssistRoute
  ApiAiNextStepRoute: typeof ApiAiNextStepRoute
  ApiAiSummaryRoute: typeof ApiAiSummaryRoute
  ApiPublicDashboardRoute: typeof ApiPublicDashboardRoute
  ApiPublicDossiersRoute: typeof ApiPublicDossiersRouteWithChildren
  ApiPublicExtractRoute: typeof ApiPublicExtractRoute
  ApiPublicFaqAssistRoute: typeof ApiPublicFaqAssistRoute
  ApiPublicTrackCodeRoute: typeof ApiPublicTrackCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/raporte': {
      id: '/raporte'
      path: '/raporte'
      fullPath: '/raporte'
      preLoaderRoute: typeof RaporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dosjet': {
      id: '/dosjet'
      path: '/dosjet'
      fullPath: '/dosjet'
      preLoaderRoute: typeof DosjetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biznes': {
      id: '/biznes'
      path: '/biznes'
      fullPath: '/biznes'
      preLoaderRoute: typeof BiznesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aplikim': {
      id: '/aplikim'
      path: '/aplikim'
      fullPath: '/aplikim'
      preLoaderRoute: typeof AplikimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$code': {
      id: '/track/$code'
      path: '/track/$code'
      fullPath: '/track/$code'
      preLoaderRoute: typeof TrackCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dosja/$id': {
      id: '/dosja/$id'
      path: '/dosja/$id'
      fullPath: '/dosja/$id'
      preLoaderRoute: typeof DosjaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aplikim/dokumentacion': {
      id: '/aplikim/dokumentacion'
      path: '/dokumentacion'
      fullPath: '/aplikim/dokumentacion'
      preLoaderRoute: typeof AplikimDokumentacionRouteImport
      parentRoute: typeof AplikimRoute
    }
    '/api/public/faq-assist': {
      id: '/api/public/faq-assist'
      path: '/api/public/faq-assist'
      fullPath: '/api/public/faq-assist'
      preLoaderRoute: typeof ApiPublicFaqAssistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/extract': {
      id: '/api/public/extract'
      path: '/api/public/extract'
      fullPath: '/api/public/extract'
      preLoaderRoute: typeof ApiPublicExtractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/dossiers': {
      id: '/api/public/dossiers'
      path: '/api/public/dossiers'
      fullPath: '/api/public/dossiers'
      preLoaderRoute: typeof ApiPublicDossiersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/dashboard': {
      id: '/api/public/dashboard'
      path: '/api/public/dashboard'
      fullPath: '/api/public/dashboard'
      preLoaderRoute: typeof ApiPublicDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/summary': {
      id: '/api/ai/summary'
      path: '/api/ai/summary'
      fullPath: '/api/ai/summary'
      preLoaderRoute: typeof ApiAiSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/next-step': {
      id: '/api/ai/next-step'
      path: '/api/ai/next-step'
      fullPath: '/api/ai/next-step'
      preLoaderRoute: typeof ApiAiNextStepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/assist': {
      id: '/api/ai/assist'
      path: '/api/ai/assist'
      fullPath: '/api/ai/assist'
      preLoaderRoute: typeof ApiAiAssistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track/$code': {
      id: '/api/public/track/$code'
      path: '/api/public/track/$code'
      fullPath: '/api/public/track/$code'
      preLoaderRoute: typeof ApiPublicTrackCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/dossiers/$id': {
      id: '/api/public/dossiers/$id'
      path: '/$id'
      fullPath: '/api/public/dossiers/$id'
      preLoaderRoute: typeof ApiPublicDossiersIdRouteImport
      parentRoute: typeof ApiPublicDossiersRoute
    }
  }
}

interface AplikimRouteChildren {
  AplikimDokumentacionRoute: typeof AplikimDokumentacionRoute
}

const AplikimRouteChildren: AplikimRouteChildren = {
  AplikimDokumentacionRoute: AplikimDokumentacionRoute,
}

const AplikimRouteWithChildren =
  AplikimRoute._addFileChildren(AplikimRouteChildren)

interface ApiPublicDossiersRouteChildren {
  ApiPublicDossiersIdRoute: typeof ApiPublicDossiersIdRoute
}

const ApiPublicDossiersRouteChildren: ApiPublicDossiersRouteChildren = {
  ApiPublicDossiersIdRoute: ApiPublicDossiersIdRoute,
}

const ApiPublicDossiersRouteWithChildren =
  ApiPublicDossiersRoute._addFileChildren(ApiPublicDossiersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminLoginRoute: AdminLoginRoute,
  AplikimRoute: AplikimRouteWithChildren,
  BiznesRoute: BiznesRoute,
  DosjetRoute: DosjetRoute,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  RaporteRoute: RaporteRoute,
  DosjaIdRoute: DosjaIdRoute,
  TrackCodeRoute: TrackCodeRoute,
  ApiAiAssistRoute: ApiAiAssistRoute,
  ApiAiNextStepRoute: ApiAiNextStepRoute,
  ApiAiSummaryRoute: ApiAiSummaryRoute,
  ApiPublicDashboardRoute: ApiPublicDashboardRoute,
  ApiPublicDossiersRoute: ApiPublicDossiersRouteWithChildren,
  ApiPublicExtractRoute: ApiPublicExtractRoute,
  ApiPublicFaqAssistRoute: ApiPublicFaqAssistRoute,
  ApiPublicTrackCodeRoute: ApiPublicTrackCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
