/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RaporteRouteImport } from './routes/raporte'
import { Route as DosjetRouteImport } from './routes/dosjet'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackCodeRouteImport } from './routes/track.$code'
import { Route as DosjaIdRouteImport } from './routes/dosja.$id'
import { Route as ApiPublicExtractRouteImport } from './routes/api/public/extract'
import { Route as ApiPublicDossiersRouteImport } from './routes/api/public/dossiers'
import { Route as ApiPublicDashboardRouteImport } from './routes/api/public/dashboard'
import { Route as ApiAiSummaryRouteImport } from './routes/api/ai/summary'
import { Route as ApiAiNextStepRouteImport } from './routes/api/ai/next-step'
import { Route as ApiAiAssistRouteImport } from './routes/api/ai/assist'
import { Route as ApiPublicTrackCodeRouteImport } from './routes/api/public/track.$code'
import { Route as ApiPublicDossiersIdRouteImport } from './routes/api/public/dossiers.$id'

const RaporteRoute = RaporteRouteImport.update({
  id: '/raporte',
  path: '/raporte',
  getParentRoute: () => rootRouteImport,
} as any)
const DosjetRoute = DosjetRouteImport.update({
  id: '/dosjet',
  path: '/dosjet',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackCodeRoute = TrackCodeRouteImport.update({
  id: '/track/$code',
  path: '/track/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const DosjaIdRoute = DosjaIdRouteImport.update({
  id: '/dosja/$id',
  path: '/dosja/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicExtractRoute = ApiPublicExtractRouteImport.update({
  id: '/api/public/extract',
  path: '/api/public/extract',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDossiersRoute = ApiPublicDossiersRouteImport.update({
  id: '/api/public/dossiers',
  path: '/api/public/dossiers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDashboardRoute = ApiPublicDashboardRouteImport.update({
  id: '/api/public/dashboard',
  path: '/api/public/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiSummaryRoute = ApiAiSummaryRouteImport.update({
  id: '/api/ai/summary',
  path: '/api/ai/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiNextStepRoute = ApiAiNextStepRouteImport.update({
  id: '/api/ai/next-step',
  path: '/api/ai/next-step',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiAssistRoute = ApiAiAssistRouteImport.update({
  id: '/api/ai/assist',
  path: '/api/ai/assist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTrackCodeRoute = ApiPublicTrackCodeRouteImport.update({
  id: '/api/public/track/$code',
  path: '/api/public/track/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDossiersIdRoute = ApiPublicDossiersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPublicDossiersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dosjet': typeof DosjetRoute
  '/raporte': typeof RaporteRoute
  '/dosja/$id': typeof DosjaIdRoute
  '/track/$code': typeof TrackCodeRoute
  '/api/ai/assist': typeof ApiAiAssistRoute
  '/api/ai/next-step': typeof ApiAiNextStepRoute
  '/api/ai/summary': typeof ApiAiSummaryRoute
  '/api/public/dashboard': typeof ApiPublicDashboardRoute
  '/api/public/dossiers': typeof ApiPublicDossiersRouteWithChildren
  '/api/public/extract': typeof ApiPublicExtractRoute
  '/api/public/dossiers/$id': typeof ApiPublicDossiersIdRoute
  '/api/public/track/$code': typeof ApiPublicTrackCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dosjet': typeof DosjetRoute
  '/raporte': typeof RaporteRoute
  '/dosja/$id': typeof DosjaIdRoute
  '/track/$code': typeof TrackCodeRoute
  '/api/ai/assist': typeof ApiAiAssistRoute
  '/api/ai/next-step': typeof ApiAiNextStepRoute
  '/api/ai/summary': typeof ApiAiSummaryRoute
  '/api/public/dashboard': typeof ApiPublicDashboardRoute
  '/api/public/dossiers': typeof ApiPublicDossiersRouteWithChildren
  '/api/public/extract': typeof ApiPublicExtractRoute
  '/api/public/dossiers/$id': typeof ApiPublicDossiersIdRoute
  '/api/public/track/$code': typeof ApiPublicTrackCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dosjet': typeof DosjetRoute
  '/raporte': typeof RaporteRoute
  '/dosja/$id': typeof DosjaIdRoute
  '/track/$code': typeof TrackCodeRoute
  '/api/ai/assist': typeof ApiAiAssistRoute
  '/api/ai/next-step': typeof ApiAiNextStepRoute
  '/api/ai/summary': typeof ApiAiSummaryRoute
  '/api/public/dashboard': typeof ApiPublicDashboardRoute
  '/api/public/dossiers': typeof ApiPublicDossiersRouteWithChildren
  '/api/public/extract': typeof ApiPublicExtractRoute
  '/api/public/dossiers/$id': typeof ApiPublicDossiersIdRoute
  '/api/public/track/$code': typeof ApiPublicTrackCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dosjet'
    | '/raporte'
    | '/dosja/$id'
    | '/track/$code'
    | '/api/ai/assist'
    | '/api/ai/next-step'
    | '/api/ai/summary'
    | '/api/public/dashboard'
    | '/api/public/dossiers'
    | '/api/public/extract'
    | '/api/public/dossiers/$id'
    | '/api/public/track/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dosjet'
    | '/raporte'
    | '/dosja/$id'
    | '/track/$code'
    | '/api/ai/assist'
    | '/api/ai/next-step'
    | '/api/ai/summary'
    | '/api/public/dashboard'
    | '/api/public/dossiers'
    | '/api/public/extract'
    | '/api/public/dossiers/$id'
    | '/api/public/track/$code'
  id:
    | '__root__'
    | '/'
    | '/dosjet'
    | '/raporte'
    | '/dosja/$id'
    | '/track/$code'
    | '/api/ai/assist'
    | '/api/ai/next-step'
    | '/api/ai/summary'
    | '/api/public/dashboard'
    | '/api/public/dossiers'
    | '/api/public/extract'
    | '/api/public/dossiers/$id'
    | '/api/public/track/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DosjetRoute: typeof DosjetRoute
  RaporteRoute: typeof RaporteRoute
  DosjaIdRoute: typeof DosjaIdRoute
  TrackCodeRoute: typeof TrackCodeRoute
  ApiAiAssistRoute: typeof ApiAiAssistRoute
  ApiAiNextStepRoute: typeof ApiAiNextStepRoute
  ApiAiSummaryRoute: typeof ApiAiSummaryRoute
  ApiPublicDashboardRoute: typeof ApiPublicDashboardRoute
  ApiPublicDossiersRoute: typeof ApiPublicDossiersRouteWithChildren
  ApiPublicExtractRoute: typeof ApiPublicExtractRoute
  ApiPublicTrackCodeRoute: typeof ApiPublicTrackCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/raporte': {
      id: '/raporte'
      path: '/raporte'
      fullPath: '/raporte'
      preLoaderRoute: typeof RaporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dosjet': {
      id: '/dosjet'
      path: '/dosjet'
      fullPath: '/dosjet'
      preLoaderRoute: typeof DosjetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$code': {
      id: '/track/$code'
      path: '/track/$code'
      fullPath: '/track/$code'
      preLoaderRoute: typeof TrackCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dosja/$id': {
      id: '/dosja/$id'
      path: '/dosja/$id'
      fullPath: '/dosja/$id'
      preLoaderRoute: typeof DosjaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/extract': {
      id: '/api/public/extract'
      path: '/api/public/extract'
      fullPath: '/api/public/extract'
      preLoaderRoute: typeof ApiPublicExtractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/dossiers': {
      id: '/api/public/dossiers'
      path: '/api/public/dossiers'
      fullPath: '/api/public/dossiers'
      preLoaderRoute: typeof ApiPublicDossiersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/dashboard': {
      id: '/api/public/dashboard'
      path: '/api/public/dashboard'
      fullPath: '/api/public/dashboard'
      preLoaderRoute: typeof ApiPublicDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/summary': {
      id: '/api/ai/summary'
      path: '/api/ai/summary'
      fullPath: '/api/ai/summary'
      preLoaderRoute: typeof ApiAiSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/next-step': {
      id: '/api/ai/next-step'
      path: '/api/ai/next-step'
      fullPath: '/api/ai/next-step'
      preLoaderRoute: typeof ApiAiNextStepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/assist': {
      id: '/api/ai/assist'
      path: '/api/ai/assist'
      fullPath: '/api/ai/assist'
      preLoaderRoute: typeof ApiAiAssistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track/$code': {
      id: '/api/public/track/$code'
      path: '/api/public/track/$code'
      fullPath: '/api/public/track/$code'
      preLoaderRoute: typeof ApiPublicTrackCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/dossiers/$id': {
      id: '/api/public/dossiers/$id'
      path: '/$id'
      fullPath: '/api/public/dossiers/$id'
      preLoaderRoute: typeof ApiPublicDossiersIdRouteImport
      parentRoute: typeof ApiPublicDossiersRoute
    }
  }
}

interface ApiPublicDossiersRouteChildren {
  ApiPublicDossiersIdRoute: typeof ApiPublicDossiersIdRoute
}

const ApiPublicDossiersRouteChildren: ApiPublicDossiersRouteChildren = {
  ApiPublicDossiersIdRoute: ApiPublicDossiersIdRoute,
}

const ApiPublicDossiersRouteWithChildren =
  ApiPublicDossiersRoute._addFileChildren(ApiPublicDossiersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DosjetRoute: DosjetRoute,
  RaporteRoute: RaporteRoute,
  DosjaIdRoute: DosjaIdRoute,
  TrackCodeRoute: TrackCodeRoute,
  ApiAiAssistRoute: ApiAiAssistRoute,
  ApiAiNextStepRoute: ApiAiNextStepRoute,
  ApiAiSummaryRoute: ApiAiSummaryRoute,
  ApiPublicDashboardRoute: ApiPublicDashboardRoute,
  ApiPublicDossiersRoute: ApiPublicDossiersRouteWithChildren,
  ApiPublicExtractRoute: ApiPublicExtractRoute,
  ApiPublicTrackCodeRoute: ApiPublicTrackCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
